### ISSUE TITLE
Supported GPUs? and Length of music?

### ISSUE THREAD

**Issue by computersrmyfriends** [iohanngrig/bachsformer#1]
Hello,
Does this have any minimum GPU requirements?

And whatis the maximum music duration it can generate music for?

Thanks

**Comment by iohanngrig** [comment]
* One needs [CUDA](https://en.wikipedia.org/wiki/CUDA) enabled [Nvidia GPU](https://developer.nvidia.com/cuda-gpus). Settings inside the config.yaml can be modified to incorporate CPUs only (or Mac specific graphical acceleration), however, the training would be significantly longer.
* Currently, generated audio duration is around a minute (192 codebook indices, which corresponds to the window length of musical segments the model is trained on). While code could be modified to accommodate longer durations, the audio won't be as coherent (beginning and ending might be completely unrelated). To avoid incoherence, models can be modified and trained on longer musical segments. However, given scarcity of data, this might not lead to desired outcome.

**Comment by computersrmyfriends** [comment]
Thanks for the response. That's helpful to know. Any plans of supporting longer durtions?

**Comment by iohanngrig** [comment]
Not at the moment.
